# Generated by Django 5.2.5 on 2026-04-09 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'Groupe A'), ('B', 'Groupe B'), ('C', 'Groupe C')], max_length=1)),
            ],
            options={
                'verbose_name': 'Groupe',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ADEIB U26 Illara', max_length=200)),
                ('edition', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tournament/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tournoi',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='tournament.group')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournament.tournament')),
            ],
            options={
                'verbose_name': 'Équipe',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('position', models.CharField(choices=[('GK', 'Gardien'), ('DEF', 'Défenseur'), ('MID', 'Milieu'), ('FWD', 'Attaquant')], default='MID', max_length=3)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('is_captain', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournament.team')),
            ],
            options={
                'verbose_name': 'Joueur',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('GROUP', 'Phase de groupes'), ('QF', 'Quart de finale'), ('SF', 'Demi-finale'), ('3RD', 'Match 3e place'), ('FINAL', 'Finale')], default='GROUP', max_length=10)),
                ('match_date', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, default='Terrain ADEIB, Illara', max_length=200)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programmé'), ('LIVE', 'En direct'), ('FINISHED', 'Terminé'), ('CANCELLED', 'Annulé')], default='SCHEDULED', max_length=10)),
                ('matchday', models.PositiveIntegerField(default=1)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournament.group')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='tournament.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='tournament.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.tournament')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
                'ordering': ['match_date'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('is_own_goal', models.BooleanField(default=False)),
                ('is_penalty', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='tournament.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='tournament.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_scored', to='tournament.team')),
            ],
            options={
                'verbose_name': 'But',
                'ordering': ['minute'],
            },
        ),
        migrations.CreateModel(
            name='KnockoutMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('QF', 'Quart de finale'), ('SF', 'Demi-finale'), ('3RD', 'Match 3e place'), ('FINAL', 'Finale')], max_length=10)),
                ('match_number', models.PositiveIntegerField(default=1)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('home_penalties', models.PositiveIntegerField(blank=True, null=True)),
                ('away_penalties', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programmé'), ('LIVE', 'En direct'), ('FINISHED', 'Terminé')], default='SCHEDULED', max_length=10)),
                ('match_date', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, default='Terrain ADEIB, Illara', max_length=200)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knockout_away', to='tournament.team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knockout_home', to='tournament.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knockout_wins', to='tournament.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knockout_matches', to='tournament.tournament')),
            ],
            options={
                'verbose_name': 'Match éliminatoire',
                'ordering': ['round', 'match_number'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournament.tournament'),
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveIntegerField(default=0)),
                ('won', models.PositiveIntegerField(default=0)),
                ('drawn', models.PositiveIntegerField(default=0)),
                ('lost', models.PositiveIntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournament.group')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournament.team')),
            ],
            options={
                'verbose_name': 'Classement',
                'ordering': ['-points', '-goals_for'],
                'unique_together': {('group', 'team')},
            },
        ),
    ]
