# Generated by Django 6.0.4 on 2026-04-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='live_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
