# Generated by Django 5.2.5 on 2026-04-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_add_live_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200, verbose_name="Nom de l'équipe")),
                ('captain_name', models.CharField(max_length=200, verbose_name='Nom du capitaine')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email (optionnel)')),
                ('neighborhood', models.CharField(max_length=200, verbose_name='Quartier / Village')),
                ('player_count', models.PositiveIntegerField(default=11, verbose_name='Nombre de joueurs')),
                ('payment_proof', models.ImageField(upload_to='registrations/', verbose_name='Preuve de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Remarques')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Refusée')], default='PENDING', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscription équipe',
                'verbose_name_plural': 'Inscriptions équipes',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
