# Generated by Django 5.2.14 on 2026-05-08 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, default=500, max_digits=10, verbose_name='Prix (FCFA)')),
                ('ticket_size', models.CharField(choices=[('small', 'Petit (10 par page)'), ('medium', 'Moyen (6 par page)'), ('large', 'Grand (4 par page)')], default='small', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=100, verbose_name='Quantité à générer')),
                ('gate_opens', models.TimeField(default='13:00', verbose_name='Ouverture des portes')),
                ('gate_closes', models.TimeField(default='19:00', verbose_name='Fermeture des portes')),
                ('ticket_text', models.CharField(blank=True, max_length=200, verbose_name='Texte additionnel')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_config', to='tournament.match')),
            ],
            options={
                'verbose_name': 'Configuration tickets',
                'verbose_name_plural': 'Configurations tickets',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True)),
                ('seat_number', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('SOLD', 'Vendu'), ('USED', 'Utilisé'), ('CANCELLED', 'Annulé')], default='AVAILABLE', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('buyer_phone', models.CharField(blank=True, max_length=20)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tournament.ticketconfig')),
            ],
            options={
                'verbose_name': 'Ticket',
                'ordering': ['ticket_number'],
            },
        ),
    ]
