# Generated by Django 5.2.14 on 2026-05-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_ticketconfig_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketconfig',
            name='ticket_size',
            field=models.CharField(choices=[('small', 'Petit (10 par page)'), ('medium', 'Moyen (6 par page)'), ('large', 'Grand (4 par page)'), ('premium', 'Premium A4 Paysage (2 par page)')], default='small', max_length=10),
        ),
    ]
