# Generated by Django 5.2.14 on 2026-05-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_alter_ticketconfig_ticket_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketconfig',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Naira (₦)'), ('XOF', 'FCFA (CFA)')], default='XOF', max_length=3, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='ticketconfig',
            name='price',
            field=models.DecimalField(decimal_places=0, default=500, max_digits=10, verbose_name='Prix'),
        ),
    ]
