# Generated by Django 6.0.1 on 2026-06-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_ticketconfig_currency_alter_ticketconfig_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='knockoutmatch',
            name='stream_platform',
            field=models.CharField(blank=True, choices=[('YOUTUBE', 'YouTube'), ('FACEBOOK', 'Facebook'), ('TWITCH', 'Twitch'), ('OTHER', 'Autre')], default='YOUTUBE', max_length=10, verbose_name='Plateforme de diffusion'),
        ),
        migrations.AddField(
            model_name='knockoutmatch',
            name='stream_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien de diffusion'),
        ),
        migrations.AddField(
            model_name='match',
            name='stream_platform',
            field=models.CharField(blank=True, choices=[('YOUTUBE', 'YouTube'), ('FACEBOOK', 'Facebook'), ('TWITCH', 'Twitch'), ('OTHER', 'Autre')], default='YOUTUBE', max_length=10, verbose_name='Plateforme de diffusion'),
        ),
        migrations.AddField(
            model_name='match',
            name='stream_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien de diffusion'),
        ),
        migrations.AlterField(
            model_name='knockoutmatch',
            name='venue',
            field=models.CharField(blank=True, default='Stade Cup Legends', max_length=200),
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(blank=True, default='Stade Cup Legends', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='Cup Legends', max_length=200),
        ),
    ]
