# Generated by Django 6.0.1 on 2026-06-05 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_knockoutmatch_stream_platform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketconfig',
            name='ticket_size',
        ),
        migrations.AddField(
            model_name='match',
            name='man_of_the_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motm_awards', to='tournament.player', verbose_name='Homme du match'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(choices=[('A', 'Groupe A'), ('B', 'Groupe B'), ('C', 'Groupe C'), ('D', 'Groupe D'), ('E', 'Groupe E'), ('F', 'Groupe F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ticketconfig',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Naira (₦)'), ('XOF', 'FCFA (CFA)')], default='NGN', max_length=3, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='ticketconfig',
            name='price',
            field=models.DecimalField(decimal_places=0, default=200, max_digits=10, verbose_name='Prix'),
        ),
    ]
