# Generated by Django 6.0.1 on 2026-06-05 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_remove_ticketconfig_ticket_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Surnom (nom de maillot)'),
        ),
        migrations.AddField(
            model_name='player',
            name='red_cards',
            field=models.PositiveIntegerField(default=0, verbose_name='Cartons rouges'),
        ),
        migrations.AddField(
            model_name='player',
            name='yellow_cards',
            field=models.PositiveIntegerField(default=0, verbose_name='Cartons jaunes'),
        ),
        migrations.AddField(
            model_name='team',
            name='coach_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Entraîneur'),
        ),
        migrations.AddField(
            model_name='team',
            name='president_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Président'),
        ),
        migrations.CreateModel(
            name='PlayerVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('vote_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='tournament.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_votes', to='tournament.tournament')),
            ],
            options={
                'verbose_name': 'Vote joueur',
                'verbose_name_plural': 'Votes joueurs',
                'ordering': ['-created_at'],
                'unique_together': {('tournament', 'device_id', 'vote_date')},
            },
        ),
    ]
