# Generated by Django 6.0.1 on 2026-06-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_player_nickname_player_red_cards_player_yellow_cards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='qualifiers_per_group',
            field=models.PositiveIntegerField(default=2, help_text="Nombre d'équipes qui sortent de chaque poule pour la phase finale.", verbose_name='Qualifiés par poule'),
        ),
    ]
