# Generated by Django 5.2.5 on 2026-04-09 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_predictions', models.PositiveIntegerField(default=0)),
                ('correct_predictions', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classement pronostics',
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(choices=[('1', 'Victoire équipe A'), ('X', 'Match nul'), ('2', 'Victoire équipe B'), ('1X', 'Victoire A ou Nul'), ('X2', 'Nul ou Victoire B'), ('12', 'Victoire A ou B')], max_length=2)),
                ('odds', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='tournament.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pronostic',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'match')},
            },
        ),
    ]
